# ===========================
# Dataset
# ===========================

image_size: 32

train_split: 0.70
val_split: 0.15
test_split: 0.15

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# ===========================
# DataLoader
# ===========================

batch_size: 32
num_workers: 2
pin_memory: true

# ===========================
# Training
# ===========================

epochs: 2
learning_rate: 0.001

# ===========================
# CNN
# ===========================

conv_channels: [32, 64, 128]

kernel_size: 3

activation: relu

dropout: 0.3

use_batchnorm: true